name: aitapp
description: L-cam flutter app

publish_to: 'none'

version: 1.3.0+4

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  async: ^2.11.0
  cupertino_icons: ^1.0.2
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_widget_from_html: ^0.14.11
  fluttertoast: ^8.2.4
  hooks_riverpod: ^2.5.1
  http: ^1.2.0
  intl: ^0.18.1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdfviewer: ^24.2.4
  system_proxy: ^0.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.25.0

flutter:
  uses-material-design: true

  assets:
    - assets/pdfs/
    - assets/html/

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/0m030eac1c725117c9692003de113f170c70ea4d21ca66.png"