name: build android

on:
  workflow_dispatch:
  push:
    branches:
    - dev
jobs:
  build_android:
    name: Build apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
            #JAVA環境構築
      - name: install java 12.x
        uses: actions/setup-java@v1
        with:
          java-version: 12.x 
      - name: setup cache
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache
      - name: Create dot env file
        shell: bash
        run: |
          mkdir env
          cd env
          touch .env
          echo "BLOWFISHKEY=${{ secrets.BLOWFISH_KEY }}" >> .env
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get flutter Package
        run: flutter pub get
      - name: build_runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build app
        run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk